# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_enclos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, sdf):
        sdf.setObjectName("sdf")
        sdf.resize(675, 615)
        self.pushButton_ajouter = QtWidgets.QPushButton(sdf)
        self.pushButton_ajouter.setGeometry(QtCore.QRect(80, 400, 121, 51))
        self.pushButton_ajouter.setObjectName("pushButton_ajouter")
        self.pushButton_modifier = QtWidgets.QPushButton(sdf)
        self.pushButton_modifier.setGeometry(QtCore.QRect(260, 400, 121, 51))
        self.pushButton_modifier.setObjectName("pushButton_modifier")
        self.pushButton_supprimer = QtWidgets.QPushButton(sdf)
        self.pushButton_supprimer.setGeometry(QtCore.QRect(420, 400, 121, 51))
        self.pushButton_supprimer.setObjectName("pushButton_supprimer")
        self.lineEdit_numenclos = QtWidgets.QLineEdit(sdf)
        self.lineEdit_numenclos.setGeometry(QtCore.QRect(90, 150, 113, 20))
        self.lineEdit_numenclos.setObjectName("lineEdit_numenclos")
        self.lineEdit_nomenclos = QtWidgets.QLineEdit(sdf)
        self.lineEdit_nomenclos.setGeometry(QtCore.QRect(240, 150, 113, 20))
        self.lineEdit_nomenclos.setObjectName("lineEdit_nomenclos")
        self.comboBox_taille = QtWidgets.QComboBox(sdf)
        self.comboBox_taille.setGeometry(QtCore.QRect(440, 140, 69, 22))
        self.comboBox_taille.setObjectName("comboBox_taille")
        self.comboBox_taille.addItem("")
        self.comboBox_taille.addItem("")
        self.comboBox_taille.addItem("")
        self.comboBox_localisation = QtWidgets.QComboBox(sdf)
        self.comboBox_localisation.setGeometry(QtCore.QRect(440, 260, 69, 22))
        self.comboBox_localisation.setObjectName("comboBox_localisation")
        self.comboBox_localisation.addItem("")
        self.comboBox_localisation.addItem("")
        self.comboBox_localisation.addItem("")
        self.label_numenclos = QtWidgets.QLabel(sdf)
        self.label_numenclos.setGeometry(QtCore.QRect(90, 123, 111, 20))
        self.label_numenclos.setObjectName("label_numenclos")
        self.label_2 = QtWidgets.QLabel(sdf)
        self.label_2.setGeometry(QtCore.QRect(240, 120, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_taille = QtWidgets.QLabel(sdf)
        self.label_taille.setGeometry(QtCore.QRect(440, 113, 81, 21))
        self.label_taille.setObjectName("label_taille")
        self.label_localisatio = QtWidgets.QLabel(sdf)
        self.label_localisatio.setGeometry(QtCore.QRect(440, 230, 121, 21))
        self.label_localisatio.setObjectName("label_localisatio")
        self.label = QtWidgets.QLabel(sdf)
        self.label.setGeometry(QtCore.QRect(60, 170, 161, 21))
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(sdf)
        self.label_3.setGeometry(QtCore.QRect(220, 170, 151, 16))
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(sdf)
        QtCore.QMetaObject.connectSlotsByName(sdf)

    def retranslateUi(self, sdf):
        _translate = QtCore.QCoreApplication.translate
        sdf.setWindowTitle(_translate("sdf", "Dialog"))
        self.pushButton_ajouter.setText(_translate("sdf", "Ajouter"))
        self.pushButton_modifier.setText(_translate("sdf", "Modifier"))
        self.pushButton_supprimer.setText(_translate("sdf", "Supprimer"))
        self.comboBox_taille.setItemText(0, _translate("sdf", "petit"))
        self.comboBox_taille.setItemText(1, _translate("sdf", "moyen"))
        self.comboBox_taille.setItemText(2, _translate("sdf", "grand"))
        self.comboBox_localisation.setItemText(0, _translate("sdf", "A"))
        self.comboBox_localisation.setItemText(1, _translate("sdf", "B"))
        self.comboBox_localisation.setItemText(2, _translate("sdf", "C"))
        self.label_numenclos.setText(_translate("sdf", "Numéro de l\'enclos"))
        self.label_2.setText(_translate("sdf", "Nom de l\'enclos"))
        self.label_taille.setText(_translate("sdf", "Taille de l\'enclos"))
        self.label_localisatio.setText(_translate("sdf", "Localisation de l\'enclos"))
        self.label.setText(_translate("sdf", "Le format du numéro est incorrect"))
        self.label_3.setText(_translate("sdf", "Le format du nom est incorrect"))
